---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-toolkit
  labels:
    app: devops-toolkit
    component: web
spec:
  selector:
    matchLabels:
      app: devops-toolkit
      component: web
